# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 305d54bb893c971a4e00e70022f252603d9e751061914bfc5b9baeb6f2403bb0954265e7032a8b4a5337c3c9f5e82c918a2269bf62e07d383fc0582641a94fe7

test:
  secret_key_base: d468c9b886fac25e8173da58f74c57151b5ce132bac8a549e8473e24e1811394b7d8e606293b51406269e3ffb28eaada598801fc0eecb884971151bfc815f21f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
